export default {
	friends: function() {
		let friendsArr = [{
				id: 1,
				imgurl: 'four.png',
				tip: 2,
				name: '大海',
				time: new Date(),
				news: 'I am leaving this comment so that even after months and years later ',
			},
			{
				id: 2,
				imgurl: 'one.png',
				tip: 2223,
				name: '山川',
				time: new Date(),
				news: 'I am leaving this comment so that even after months and years later ',
			},
			{
				id: 3,
				imgurl: 'two.png',
				tip: 2,
				name: '河流',
				time: new Date(),
				news: 'I am leaving this comment so that even after months and years later ',
			},
			{
				id: 4,
				imgurl: 'three.png',
				tip: 2,
				name: '溪流',
				time: new Date(),
				news: 'I am leaving this comment so that even after months and years later ',
			},
			{
				id: 1,
				imgurl: 'four.png',
				tip: 2,
				name: '大海',
				time: new Date(),
				news: 'I am leaving this comment so that even after months and years later ',
			},
			{
				id: 2,
				imgurl: 'one.png',
				tip: 2,
				name: '山川',
				time: new Date(),
				news: 'I am leaving this comment so that even after months and years later ',
			},
			{
				id: 3,
				imgurl: 'two.png',
				tip: 2,
				name: '河流',
				time: new Date(),
				news: 'I am leaving this comment so that even after months and years later ',
			},
			{
				id: 4,
				imgurl: 'three.png',
				tip: 2,
				name: '溪流',
				time: new Date(),
				news: 'I am leaving this comment so that even after months and years later ',
			},
			{
				id: 1,
				imgurl: 'four.png',
				tip: 2,
				name: '大海',
				time: new Date(),
				news: 'I am leaving this comment so that even after months and years later ',
			},
			{
				id: 2,
				imgurl: 'one.png',
				tip: 2,
				name: '山川',
				time: new Date(),
				news: 'I am leaving this comment so that even after months and years later ',
			},
			{
				id: 3,
				imgurl: 'two.png',
				tip: 2,
				name: '河流',
				time: new Date(),
				news: 'I am leaving this comment so that even after months and years later ',
			},
			{
				id: 4,
				imgurl: 'three.png',
				tip: 2,
				name: '溪流',
				time: new Date(),
				news: 'I am leaving this comment so that even after months and years later ',
			},
		];
		return friendsArr;
	}
}
